FROM debian:__DIST__

ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb http://packages.groonga.org/debian/ __DIST__ main" > /etc/apt/sources.list.d/groonga.list
RUN echo "deb-src http://packages.groonga.org/debian/ __DIST__ main" >> /etc/apt/sources.list.d/groonga.list

RUN apt-get update
RUN apt-get -y --allow-unauthenticated install groonga-keyring; apt-get update
RUN apt-get -y install mysql-server-mroonga
RUN apt-get -y install groonga-tokenizer-mecab
ADD init /
ADD etc/ etc/

CMD ["/init"]
