#!/bin/bash
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND

function stop() {
  pidfile="`mysqld --help --verbose 2>/dev/null |egrep '^pid-file' | awk '{print $2}'`"
  echo "Signal recieved, shutting down mysqld."
  test -f "$pidfile" || return
  kill -TERM `< $pidfile`
}

trap stop TERM INT QUIT

if [ -d /var/run/mysqld -a `stat -c %U /var/run/mysqld` != 'mysql' ]; then
  chown mysql /var/run/mysqld
fi

if [ ! -d /var/lib/mysql/mysql ]; then
  echo "Mysql database is missing, run initial configure..."
  /var/lib/dpkg/info/mysql-server-5.5.postinst configure
  echo "configure done"
fi

echo "Starting mysqld to check environment"
/etc/init.d/mysql start

if !(echo 'show engines' | mysql -u root | grep -q 'mroonga'); then
  echo -n "Installing Mroonga plugin..."
  mysql -u root << EOS
    INSTALL PLUGIN mroonga SONAME 'ha_mroonga.so';
    CREATE FUNCTION last_insert_grn_id RETURNS INTEGER SONAME 'ha_mroonga.so';
    CREATE FUNCTION mroonga_snippet RETURNS STRING SONAME 'ha_mroonga.so';
    CREATE FUNCTION mroonga_command RETURNS STRING SONAME 'ha_mroonga.so';
    CREATE FUNCTION mroonga_escape RETURNS STRING SONAME 'ha_mroonga.so';
EOS
  echo "done"
else
  echo "Mroonga plugin is already installed."
fi 

echo "Waiting mysqld stop..."
/etc/init.d/mysql stop 2>&1
while /usr/bin/mysqladmin status > /dev/null 2> /dev/null; do
  sleep 1
done
echo "OK, now start mysqld again"
/usr/bin/mysqld_safe --skip-syslog &
wait
